### ISSUE TITLE
Unclear meaning of greyed-out About/Innovation links in the header.

### ISSUE THREAD

**Issue by lschmelzeisen** [semanux/website#16]
People might be surprised about the greyed-out About/Innovation links in the header. We could make this more clear by having a small pop-up with "under construction" when hovering/clicking on them.

**Comment by raphaelmenges** [comment]
As intermediate solution, "Innovation" and "About" are now linked to anchors on the frontpage with dd96f7eaccf11407771e2e96c6e09b85ec64dcfc. This seems feasible for me until #5 and #6 are done. Thus, I am closing this issue.
